# Generated by Django 5.2.3 on 2025-07-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapcategory', '0001_initial'),
        ('aapstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwomen',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aapcategory.designer'),
        ),
    ]
