# Generated by Django 5.2.4 on 2025-08-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapstore', '0003_gender_cart_product_gender_variation_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
