# Generated by Django 5.2.4 on 2025-12-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapstore', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
