# Generated by Django 5.2.4 on 2026-04-03 08:48

from django.db import migrations, models


def populate_existing_payment_statuses(apps, schema_editor):
    Order = apps.get_model('aapstore', 'Order')
    Order.objects.filter(payment_method='cash').update(payment_status='Pending')
    Order.objects.exclude(payment_method='cash').update(payment_status='Paid')


class Migration(migrations.Migration):

    dependencies = [
        ('aapstore', '0013_productrating_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refund In Process', 'Refund In Process'), ('Refunded', 'Refunded'), ('Failed', 'Failed')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('Not Required', 'Not Required'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Not Required', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('No Return', 'No Return'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Picked Up', 'Picked Up'), ('Received', 'Received'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='No Return', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('qrcode', 'QR Code'), ('cash', 'Cash')], max_length=50),
        ),
        migrations.RunPython(populate_existing_payment_statuses, migrations.RunPython.noop),
    ]
