# Generated by Django 5.2.4 on 2026-04-03 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_order_location_and_vendor(apps, schema_editor):
    Order = apps.get_model('aapstore', 'Order')
    OrderItem = apps.get_model('aapstore', 'OrderItem')
    from django.contrib.contenttypes.models import ContentType

    for order in Order.objects.all().iterator():
        updated_fields = []
        if not order.district:
            order.district = order.city
            updated_fields.append('district')
        if not order.country:
            order.country = 'India'
            updated_fields.append('country')
        if updated_fields:
            order.save(update_fields=updated_fields)

    for order_item in OrderItem.objects.filter(vendor__isnull=True).iterator():
        content_type = ContentType.objects.db_manager(schema_editor.connection.alias).filter(
            pk=order_item.content_type_id
        ).first()
        model_class = content_type.model_class() if content_type else None
        if not model_class:
            continue

        product = model_class.objects.filter(pk=order_item.object_id).only('vendor_id').first()
        vendor_id = getattr(product, 'vendor_id', None)
        if vendor_id:
            order_item.vendor_id = vendor_id
            order_item.save(update_fields=['vendor'])


class Migration(migrations.Migration):

    dependencies = [
        ('aapstore', '0014_order_payment_notes_order_payment_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_order_location_and_vendor, migrations.RunPython.noop),
    ]
