# Generated by Django 5.2.4 on 2026-04-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapstore', '0017_order_delivery_assigned_at_order_delivery_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_receipt_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='account_receipt_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='account_receipt_status',
            field=models.CharField(choices=[('Not Received', 'Not Received'), ('Pending Verification', 'Pending Verification'), ('Received in Account', 'Received in Account'), ('Failed', 'Failed')], default='Not Received', max_length=30),
        ),
    ]
