# Generated by Django 5.2.3 on 2025-07-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapcategory', '0001_initial'),
        ('appwomens', '0002_alter_newproduct_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproduct',
            name='description',
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='designer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='womens_products', to='aapcategory.designer'),
            preserve_default=False,
        ),
    ]
