# Generated by Django 5.2.3 on 2025-07-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0003_remove_newproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproduct',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bags',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dresses',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='footwear',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Free Size', 'Free Size')], max_length=50)),
                ('color', models.CharField(choices=[('-', '-'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Grey', 'Grey'), ('Multi Color', 'Multi Color'), ('Pink', 'Pink'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Blank', 'Blank')], max_length=50)),
                ('stock', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='appwomens.newproduct')),
            ],
        ),
    ]
