# Generated by Django 5.2.3 on 2025-07-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0004_newproduct_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soapitems',
            name='fragrance',
        ),
        migrations.RemoveField(
            model_name='soapitems',
            name='price',
        ),
        migrations.RemoveField(
            model_name='soapitems',
            name='soap_type',
        ),
        migrations.RemoveField(
            model_name='soapitems',
            name='weight',
        ),
    ]
