# Generated by Django 5.2.3 on 2025-07-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0005_remove_soapitems_fragrance_remove_soapitems_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appwomens.newproduct')),
            ],
        ),
    ]
