# Generated by Django 5.2.3 on 2025-07-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0006_shops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoapItems',
        ),
    ]
