# Generated by Django 5.2.3 on 2025-07-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0007_delete_soapitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
