# Generated by Django 5.2.3 on 2025-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0008_shops_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='is_vasu_soap',
            field=models.BooleanField(default=False),
        ),
    ]
