# Generated by Django 5.2.3 on 2025-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0009_shops_is_vasu_soap'),
    ]

    operations = [
        migrations.AddField(
            model_name='kendalls_editions',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
