# Generated by Django 5.2.3 on 2025-07-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0010_kendalls_editions_is_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kendalls_editions',
            name='edition_price',
        ),
        migrations.RemoveField(
            model_name='kendalls_editions',
            name='is_trending',
        ),
        migrations.RemoveField(
            model_name='kendalls_editions',
            name='product',
        ),
        migrations.AddField(
            model_name='kendalls_editions',
            name='edition_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
