# Generated by Django 5.2.3 on 2025-07-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0011_remove_kendalls_editions_edition_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kendalls_editions',
            name='edition_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='kendalls_editions',
            name='edition_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
