# Generated by Django 5.2.3 on 2025-07-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0012_alter_kendalls_editions_edition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
