# Generated by Django 5.2.3 on 2025-07-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0013_alter_productvariation_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
