# Generated by Django 5.2.3 on 2025-07-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0014_alter_productvariation_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproduct',
            name='stock',
        ),
    ]
