# Generated by Django 5.2.3 on 2025-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0015_remove_newproduct_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='category_type',
            field=models.CharField(blank=True, choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('dresses', 'Dresses'), ('accessories', 'Accessories'), ('bags', 'Bags'), ('beauty', 'Beauty Products')], max_length=20),
        ),
    ]
