# Generated by Django 5.2.3 on 2025-07-12 04:16

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0016_productvariation_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beautyproducts',
            name='type',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='type',
            field=models.CharField(default=1, verbose_name=builtins.max),
            preserve_default=False,
        ),
    ]
