# Generated by Django 5.2.3 on 2025-07-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0017_remove_beautyproducts_type_productvariation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='color',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='type',
        ),
        migrations.RemoveField(
            model_name='bags',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bags',
            name='type',
        ),
    ]
