# Generated by Django 5.2.3 on 2025-07-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0018_remove_accessories_color_remove_accessories_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='category_type',
            field=models.CharField(blank=True, choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('dresses', 'Dresses'), ('accessories', 'Accessories'), ('bags', 'Bags'), ('beauty', 'Beauty Products')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
