# Generated by Django 5.2.4 on 2025-08-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0020_bags_color_bags_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessories',
            name='size',
            field=models.CharField(choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Free Size', 'Free Size')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beautyproducts',
            name='color',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beautyproducts',
            name='size',
            field=models.CharField(choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Free Size', 'Free Size')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
