# Generated by Django 5.2.4 on 2025-10-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0021_accessories_color_accessories_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='size',
            field=models.CharField(blank=True, choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Free Size', 'Free Size')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bags',
            name='size',
            field=models.CharField(blank=True, choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Free Size', 'Free Size')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beautyproducts',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beautyproducts',
            name='size',
            field=models.CharField(blank=True, choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Free Size', 'Free Size')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products'),
        ),
    ]
