# Generated by Django 5.2.4 on 2025-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwomens', '0022_alter_accessories_size_alter_bags_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='type',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
