# Generated by Django 5.2.3 on 2025-07-18 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
