# Generated by Django 5.2.4 on 2025-07-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0010_account_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_verified',
        ),
    ]
