# Generated by Django 5.2.4 on 2026-04-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0012_account_account_type_vendorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('delivery_partner', 'Delivery Partner'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
