# Generated by Django 5.2.3 on 2025-07-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aapcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('designer', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('front_image', models.ImageField(upload_to='photos/products')),
                ('back_image', models.ImageField(upload_to='photos/products')),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('gender', models.CharField(default='Men', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mens_products', to='aapcategory.category')),
            ],
            options={
                'verbose_name': 'New Product',
                'verbose_name_plural': 'New Products',
            },
        ),
        migrations.CreateModel(
            name='Hometemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('template_description', models.TextField(blank=True, max_length=500)),
                ('template_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('template_image', models.ImageField(upload_to='photos/hometemplates')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Happenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.CharField(max_length=200)),
                ('edition_description', models.TextField(blank=True, max_length=500)),
                ('edition_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edition_image', models.ImageField(upload_to='photos/happenings')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')], max_length=50)),
                ('color', models.CharField(choices=[('-', '-'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Grey', 'Grey'), ('Multi Color', 'Multi Color'), ('Pink', 'Pink'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Blank', 'Blank')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Dresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Free Size', 'Free Size')], max_length=50)),
                ('color', models.CharField(choices=[('-', '-'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Grey', 'Grey'), ('Multi Color', 'Multi Color'), ('Pink', 'Pink'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Blank', 'Blank')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('Free Size', 'Free Size')], max_length=50)),
                ('color', models.CharField(choices=[('-', '-'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Grey', 'Grey'), ('Multi Color', 'Multi Color'), ('Pink', 'Pink'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Blank', 'Blank')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('-', '-'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Grey', 'Grey'), ('Multi Color', 'Multi Color'), ('Pink', 'Pink'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Blank', 'Blank')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('-', '-'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Grey', 'Grey'), ('Multi Color', 'Multi Color'), ('Pink', 'Pink'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Blank', 'Blank')], max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SoapItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soap_type', models.CharField(max_length=100)),
                ('fragrance', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmens.newproduct')),
            ],
        ),
    ]
