# Generated by Django 5.2.3 on 2025-07-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapcategory', '0001_initial'),
        ('appmens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mens_products', to='aapcategory.designer'),
        ),
    ]
