# Generated by Django 5.2.3 on 2025-07-07 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapcategory', '0001_initial'),
        ('appmens', '0002_alter_newproduct_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mens_products', to='aapcategory.designer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='gender',
            field=models.CharField(default='Women', max_length=10),
        ),
    ]
