# Generated by Django 5.2.3 on 2025-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0003_alter_newproduct_designer_alter_newproduct_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='happenings',
            name='edition_description',
        ),
        migrations.RemoveField(
            model_name='happenings',
            name='edition_image',
        ),
        migrations.RemoveField(
            model_name='happenings',
            name='edition_name',
        ),
        migrations.RemoveField(
            model_name='happenings',
            name='edition_price',
        ),
        migrations.RemoveField(
            model_name='happenings',
            name='product',
        ),
        migrations.AddField(
            model_name='happenings',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='happenings',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/mens_features/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='happenings',
            name='link_text',
            field=models.CharField(default='Read More', max_length=50),
        ),
        migrations.AddField(
            model_name='happenings',
            name='link_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='happenings',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
