# Generated by Django 5.2.3 on 2025-07-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0004_remove_happenings_edition_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='happenings',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='happenings',
            name='link_url',
        ),
    ]
