# Generated by Django 5.2.3 on 2025-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0006_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='category_type',
            field=models.CharField(blank=True, choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('dresses', 'Dresses'), ('accessories', 'Accessories'), ('bags', 'Bags'), ('beauty', 'Beauty Products')], max_length=50, null=True),
        ),
    ]
