# Generated by Django 5.2.3 on 2025-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0007_productvariation_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='color',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='type',
        ),
        migrations.RemoveField(
            model_name='bags',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bags',
            name='type',
        ),
        migrations.RemoveField(
            model_name='newproduct',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footwear',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='gender',
            field=models.CharField(default='Mens', max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='category_type',
            field=models.CharField(blank=True, choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('dresses', 'Dresses'), ('accessories', 'Accessories'), ('bags', 'Bags'), ('beauty', 'Beauty Products')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
