# Generated by Django 5.2.3 on 2025-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0008_remove_accessories_color_remove_accessories_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='hometemplate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='hometemplate',
            name='template_description',
        ),
        migrations.RemoveField(
            model_name='hometemplate',
            name='template_image',
        ),
        migrations.RemoveField(
            model_name='hometemplate',
            name='template_name',
        ),
        migrations.RemoveField(
            model_name='hometemplate',
            name='template_price',
        ),
        migrations.AddField(
            model_name='hometemplate',
            name='home_template_image',
            field=models.ImageField(default=1, upload_to='photos/home_template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometemplate',
            name='product_type',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories'), ('Dresses', 'Dresses'), ('Bags', 'Bags'), ('Sale', 'Sale')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothing',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
