# Generated by Django 5.2.3 on 2025-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0009_alter_newproduct_options_remove_hometemplate_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
