# Generated by Django 5.2.3 on 2025-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0010_alter_productvariation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bags',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
