# Generated by Django 5.2.3 on 2025-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0011_accessories_color_bags_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='type',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
