# Generated by Django 5.2.3 on 2025-07-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0012_remove_productvariation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
