# Generated by Django 5.2.4 on 2025-08-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0014_alter_accessories_color_alter_bags_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bags',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
