# Generated by Django 5.2.4 on 2025-10-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmens', '0015_accessories_size_bags_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='product_type',
        ),
    ]
